var HORSE_WIDTH_PERCENTAGE = .2
var HORSE_SIZE_RATIO = .63

var HORSE_SPEED_DEFAULT_RATIO = .002
var HORSE_SPEED_SPRINT_RATIO = .006
var HORSE_SPEED_RATIO = HORSE_SPEED_DEFAULT_RATIO

var HORSE_SPRINT_DISTANCE = 50 

var HORSE_INFO_OFFSET_X = 0.32
var HORSE_INFO_OFFSET_Y = 0.325

var TRACK_HORSE_START_X = 0
var TRACK_HORSE_START_Y = .4 

var BACKGROUND_SCROLL_SPEED = .005
var BACKGROUND_HEIGHT = .6
var RUNWAY_HEIGHT = .4
var FOREGROUND_HEIGHT = .05

var FINISH_LINE_WIDTH = .02
var FINISH_LINE_MOVE_IN_SPEED = .005
var FINISH_LINE_MOVE_IN_POSITION = .1

var STATIC_SCROLL_SPEED = 400

var HUD_TOP_WIDTH = 0.9 
var HUD_TOP_HEIGHT = 0.2 
var HUD_ICON_PROGRESS_SPEED = (100 / (30 * 60))
var HUD_POST_SCREEN_ROW_HEIGHT = .1
var HUD_POST_SCREEN_FADE_TIME = 1000
 
var STAGE_PRE_RACE = 1 
var STAGE_IN_RACE = 2
var STAGE_FINISH_RACE = 3
var STAGE_POST_RACE = 4 

var HORSE_NAMES = {
	1 : "RED", 
	2 : "GREEN", 
	3 : "BLUE", 
	4 : "GOLD", 
	5 : "PURPLE", 
	6 : "BLACK",
}

var POSITION_NAMES = {
	1 : "1st", 
	2 : "2nd", 
	3 : "3rd", 
	4 : "4th", 
	5 : "5th", 
	6 : "6th",
}